import names from "@/data/random-names.json";
import avatars from "@/data/avatars.json";

// Local avatar library — files live in /public/preview/Avatar and are listed
// in data/avatars.json (regenerated by scripts/gen-avatars.mjs on predev/prebuild).
const AVATAR_DIR = "/preview/Avatar";
const AVATAR_FILES = avatars as string[];

function toAvatarUrl(n: number): string {
  if (AVATAR_FILES.length === 0) return "";
  const idx = n % AVATAR_FILES.length;
  return `${AVATAR_DIR}/${AVATAR_FILES[idx]}`;
}

/** djb2 string hash → positive integer */
function hashStr(s: string): number {
  let h = 5381;
  for (let i = 0; i < s.length; i++)
    h = ((h << 5) + h) ^ s.charCodeAt(i);
  return Math.abs(h);
}

/**
 * Returns a random name + avatar URL pair.
 * Pass `seed` for deterministic output (e.g. restoring a saved asset).
 */
export function getRandomUserProfile(seed?: number): {
  name: string;
  avatarUrl: string;
} {
  const i = seed ?? Math.floor(Math.random() * 10_000);
  return {
    name:      names[i % names.length],
    avatarUrl: toAvatarUrl(i),
  };
}

/**
 * Derives a stable avatar for a manually entered name.
 * Same name always produces the same avatar (hash-based).
 */
export function getAvatarForName(name: string): string {
  return toAvatarUrl(hashStr(name.trim().toLowerCase()));
}
