import { brand } from "@/lib/tokens/brand";

export const CONCEPT_UI_CANVAS_WIDTH = 1600;
export const CONCEPT_UI_CANVAS_HEIGHT = 1000;

export const conceptSceneTokens = {
  color: {
    page: brand.color.concept.page,
    app: brand.color.concept.app,
    surface: brand.color.concept.surface,
    evidenceSurface: brand.color.concept.evidenceSurface,
    surfaceStrong: brand.color.concept.surfaceStrong,
    border: brand.color.concept.border,
    borderStrong: brand.color.concept.borderStrong,
    text: brand.color.concept.text,
    muted: brand.color.concept.muted,
    faint: brand.color.concept.faint,
    inverse: brand.color.concept.inverse,
    ink: brand.color.concept.ink,
    ai: brand.color.concept.ai,
    aiSoft: brand.color.concept.aiSoft,
    goodSoft: brand.color.concept.goodSoft,
    goodText: brand.color.concept.goodText,
    warnSoft: brand.color.concept.warnSoft,
    warnText: brand.color.concept.warnText,
    info: brand.color.concept.info,
    success: brand.color.concept.success,
    warning: brand.color.concept.warning,
    error: brand.color.concept.error,
    gate: brand.color.concept.gate,
  },
  font: {
    sans: brand.font.productUi,
    weight: brand.font.weight,
  },
  typography: {
    lineHeight: brand.typography.lineHeight,
  },
  radius: {
    none: brand.spacing[0],
    sm: brand.radius[10],
    md: brand.radius[16],
    lg: brand.radius[24],
    xl: brand.radius[32],
    full: brand.radius.full,
  },
  control: {
    pill: {
      minHeight: brand.spacing[26],
      compactMinHeight: brand.spacing[22],
      denseMinHeight: brand.spacing[24],
      largeMinHeight: brand.spacing[40],
      menuMinHeight: brand.spacing[36],
      paddingY: brand.spacing[3],
      paddingX: brand.spacing[12],
      radius: brand.radius[9],
      fontSize: brand.typography.size[13],
      compactFontSize: brand.typography.size[11],
      largeFontSize: brand.typography.size[15],
      lineHeight: brand.typography.lineHeight.compact,
    },
    toolbarButton: {
      height: brand.spacing[36],
      minWidth: brand.spacing[36],
      radius: brand.radius[11],
      paddingX: brand.spacing[10],
      widePaddingX: brand.spacing[13],
      fontSize: brand.typography.size[15],
    },
    actionButton: {
      minHeight: brand.spacing[40],
      paddingX: brand.spacing[22],
      radius: brand.radius[14],
    },
  },
  momentResponse: {
    study: {
      frame: {
        width: 1000,
        height: 920,
        heightWithoutReviewer: 800,
      },
      card: {
        radius: brand.radius[42],
        paddingTop: brand.spacing[64],
        paddingX: brand.spacing[64],
        paddingBottom: brand.spacing[56],
      },
      meta: {
        top: brand.spacing[64],
        gap: brand.spacing[16],
        avatar: brand.spacing[48],
      },
      responseBox: {
        top: brand.spacing[40],
        minHeight: 258,
        radius: brand.radius[20],
        paddingX: brand.spacing[36],
        paddingY: brand.spacing[34],
        borderWidth: 2,
      },
      evidence: {
        top: brand.spacing[26],
        radius: brand.radius[24],
        paddingTop: brand.spacing[36],
        paddingX: brand.spacing[40],
        paddingBottom: brand.spacing[32],
        rowsTop: brand.spacing[20],
        rowGap: brand.spacing[14],
        iconSize: brand.spacing[26],
      },
      actions: {
        top: brand.spacing[32],
        gap: brand.spacing[16],
        height: brand.spacing[64],
        radius: brand.radius[16],
        paddingX: brand.spacing[28],
      },
    },
    title: {
      fontSize: brand.typography.size[40],
      fontWeight: brand.font.weight.semibold,
      lineHeight: brand.typography.lineHeight.compact,
    },
    metaLabel: {
      fontSize: brand.typography.size[30],
      fontWeight: brand.font.weight.regular,
      lineHeight: brand.typography.lineHeight.normal,
    },
    metaValue: {
      fontSize: brand.typography.size[28],
      fontWeight: brand.font.weight.semibold,
      lineHeight: brand.typography.lineHeight.normal,
    },
    avatarText: {
      fontSize: brand.typography.size[18],
      fontWeight: brand.font.weight.semibold,
    },
    response: {
      fontSize: brand.typography.size[34],
      fontWeight: brand.font.weight.regular,
      lineHeight: brand.typography.lineHeight.relaxed,
    },
    evidenceHeading: {
      fontSize: brand.typography.size[28],
      fontWeight: brand.font.weight.semibold,
      lineHeight: brand.typography.lineHeight.normal,
    },
    evidenceLabel: {
      fontSize: brand.typography.size[28],
      fontWeight: brand.font.weight.regular,
      lineHeight: brand.typography.lineHeight.normal,
    },
    evidenceMatch: {
      fontSize: brand.typography.size[24],
      fontWeight: brand.font.weight.regular,
      lineHeight: brand.typography.lineHeight.normal,
    },
    button: {
      fontSize: brand.typography.size[28],
      primaryWeight: brand.font.weight.medium,
      secondaryWeight: brand.font.weight.medium,
      lineHeight: brand.typography.lineHeight.normal,
    },
  },
  momentApproval: {
    title: {
      fontSize: brand.typography.size[28],
      fontWeight: brand.font.weight.semibold,
      lineHeight: brand.typography.lineHeight.compact,
    },
    eyebrow: {
      fontSize: brand.typography.size[12],
      fontWeight: brand.font.weight.semibold,
      lineHeight: brand.typography.lineHeight.compact,
    },
    stepIcon: {
      columnWidth: brand.spacing[32],
      size: brand.spacing[22],
      strokeWidth: 2.4,
    },
    stepLabel: {
      fontSize: brand.typography.size[20],
      fontWeight: brand.font.weight.medium,
      lineHeight: brand.typography.lineHeight.normal,
    },
    stepMeta: {
      fontSize: brand.typography.size[14],
      fontWeight: brand.font.weight.medium,
      lineHeight: brand.typography.lineHeight.normal,
    },
    gateTitle: {
      fontSize: brand.typography.size[22],
      fontWeight: brand.font.weight.semibold,
      lineHeight: brand.typography.lineHeight.normal,
    },
    gateDetail: {
      fontSize: brand.typography.size[15],
      fontWeight: brand.font.weight.regular,
      lineHeight: brand.typography.lineHeight.normal,
    },
    button: {
      fontSize: brand.typography.size[16],
      primaryWeight: brand.font.weight.medium,
      secondaryWeight: brand.font.weight.medium,
    },
    bodyType: {
      label: {
        fontSize: brand.typography.size[13],
        fontWeight: brand.font.weight.semibold,
        lineHeight: brand.typography.lineHeight.normal,
      },
      text: {
        fontSize: brand.typography.size[20],
        fontWeight: brand.font.weight.regular,
        lineHeight: brand.typography.lineHeight.body,
      },
      meta: {
        fontSize: brand.typography.size[15],
        fontWeight: brand.font.weight.medium,
        lineHeight: brand.typography.lineHeight.normal,
      },
    },
    details: {
      frame: {
        width: 820,
        height: 720,
      },
      panel: {
        radius: brand.radius[18],
        paddingX: brand.spacing[32],
        paddingBottom: brand.spacing[64],
      },
      header: {
        paddingTop: brand.spacing[28],
        paddingBottom: brand.spacing[26],
        gap: brand.spacing[24],
        iconSize: brand.spacing[22],
        iconStrokeWidth: 2,
        title: {
          fontSize: brand.typography.size[28],
          fontWeight: brand.font.weight.semibold,
          lineHeight: brand.typography.lineHeight.compact,
        },
      },
      content: {
        paddingTop: brand.spacing[34],
      },
      sectionTitle: {
        fontSize: brand.typography.size[22],
        fontWeight: brand.font.weight.semibold,
        lineHeight: brand.typography.lineHeight.normal,
      },
      info: {
        top: brand.spacing[22],
        rowGap: brand.spacing[10],
        gap: brand.spacing[24],
        labelWidth: 156,
        label: {
          fontSize: brand.typography.size[18],
          fontWeight: brand.font.weight.medium,
          lineHeight: brand.typography.lineHeight.normal,
        },
        value: {
          fontSize: brand.typography.size[18],
          fontWeight: brand.font.weight.regular,
          lineHeight: brand.typography.lineHeight.normal,
        },
      },
      badge: {
        height: brand.spacing[28],
        radius: brand.radius[7],
        paddingX: brand.spacing[10],
        fontSize: brand.typography.size[15],
        fontWeight: brand.font.weight.medium,
        letterSpacing: 0.5,
      },
      activity: {
        sectionTop: brand.spacing[60],
        timelineOnlyTop: brand.spacing[40],
        top: brand.spacing[26],
        rowGap: brand.spacing[26],
        rowMinHeight: brand.spacing[72],
        mutedOpacity: 0.36,
        tagHeight: brand.spacing[32],
        tagRadius: brand.radius[7],
        tagPaddingX: brand.spacing[10],
        tagFontSize: brand.typography.size[16],
        tagWeight: brand.font.weight.semibold,
        textTop: brand.spacing[8],
        textFontSize: brand.typography.size[22],
        textWeight: brand.font.weight.regular,
        textLineHeight: brand.typography.lineHeight.normal,
        timelineOnly: {
          sectionTop: brand.spacing[52],
          rowGap: brand.spacing[34],
          rowMinHeight: brand.spacing[92],
          tagHeight: brand.spacing[40],
          tagRadius: brand.radius[10],
          tagPaddingX: brand.spacing[10],
          tagFontSize: brand.typography.size[17],
          textTop: brand.spacing[10],
          textFontSize: brand.typography.size[22],
          textLineHeight: brand.typography.lineHeight.normal,
        },
      },
      timeline: {
        columnWidth: brand.spacing[48],
        gap: brand.spacing[8],
        dot: brand.spacing[8],
        dotTop: brand.spacing[12],
        lineTop: brand.spacing[26],
        timelineOnly: {
          columnWidth: brand.spacing[56],
          gap: brand.spacing[14],
          dot: brand.spacing[10],
          dotTop: brand.spacing[14],
          lineTop: brand.spacing[30],
        },
      },
    },
    study: {
      frame: {
        width: 1600,
        height: 1000,
      },
      backCard: {
        left: 56,
        top: 0,
        right: 56,
        height: 720,
        radius: brand.radius[38],
      },
      header: {
        paddingX: 50,
        paddingTop: 27,
        paddingBottom: 24,
        title: {
          fontSize: brand.typography.size[36],
          fontWeight: brand.font.weight.bold,
          lineHeight: brand.typography.lineHeight.compact,
        },
      },
      frontCard: {
        top: 108,
        radius: brand.radius[42],
        padding: 28,
      },
      trailPanel: {
        radius: brand.radius[34],
        paddingX: brand.spacing[26],
        paddingY: brand.spacing[34],
        pillHeight: brand.spacing[44],
        pillRadius: brand.radius[11],
        pillPaddingX: 20,
        pillFontSize: brand.typography.size[24],
        pillWeight: brand.font.weight.regular,
        listTop: 20,
        listRadius: brand.radius[26],
        listPaddingX: 38,
        listPaddingY: 18,
        rowHeight: 64,
        iconSize: 34,
        iconGlyphSize: 20,
        iconStrokeWidth: 4,
        labelFontSize: brand.typography.size[30],
        labelWeight: brand.font.weight.regular,
        metaFontSize: brand.typography.size[22],
        metaWeight: brand.font.weight.regular,
      },
      gatePanel: {
        top: 20,
        radius: brand.radius[30],
        paddingX: 36,
        paddingY: 25,
        titleFontSize: brand.typography.size[30],
        titleWeight: brand.font.weight.semibold,
        detailFontSize: brand.typography.size[20],
        detailWeight: brand.font.weight.regular,
        buttonHeight: 58,
        buttonRadius: brand.radius[14],
        buttonPaddingX: 26,
        buttonFontSize: brand.typography.size[24],
      },
      body: {
        noteMinHeight: 256,
        messageMinHeight: 256,
        iconSize: 30,
      },
    },
  },
  borderWidth: {
    none: brand.spacing[0],
  },
  shadow: {
    none: "none",
    card: brand.elevation.conceptCard,
    float: brand.elevation.conceptFloat,
    compactFloat: brand.elevation.conceptCompactFloat,
    studyFloat: brand.elevation.conceptStudyFloat,
    studyBack: brand.elevation.conceptStudyBack,
    active: brand.elevation.conceptActive,
    highlighted: brand.elevation.conceptActiveSmall,
    cursor: brand.elevation.conceptDrop,
    modal: brand.elevation.conceptModal,
  },
  overlay: {
    modal: brand.color.concept.modalOverlay,
  },
  background: {
    gridDot: `radial-gradient(${brand.color.concept.gridDot} 1px, transparent 1px)`,
  },
} as const;

export const avatarPalette = brand.avatarPalette;
